CREATE TABLE users (
  uid INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  firstname VARCHAR(100) NOT NULL,
  lastname VARCHAR(100) NOT NULL,
  email VARCHAR(120) NOT NULL UNIQUE,
  pwdhash VARCHAR(100) NOT NULL
);

CREATE TABLE contacts (
  cid INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  firstname VARCHAR(100) NOT NULL,
  lastname VARCHAR(100) NOT NULL,
  email VARCHAR(120) NOT NULL
);